version: "3.9"

services:
  cube_frontend:
    container_name: ${PROJECT_NAME}_frontend
    build:
      context: .
      dockerfile: ${MICROSERVICE_DOCKERFILE}
    image: ${PROJECT_NAME}_frontend
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      NODE_ENV: ${NODE_ENV}
      GENERATE_SOURCEMAP: ${GENERATE_SOURCEMAP}
      PORT: ${PORT}
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      REACT_APP_AUTH_SERVICE_URL: ${REACT_APP_AUTH_SERVICE_URL}
    volumes:
      - ./.env.example:/work/.env.example
      - ./${ENV_FILE}:/work/.env
      - ./.eslintignore:/work/.eslintignore
      - ./.eslintrc.json:/work/.eslintrc.json
      - ./.prettierignore:/work/.prettierignore
      - ./.prettierrc:/work/.prettierrc
      - ./package.json:/work/package.json
      - ./package-lock.json:/work/package-lock.json
      - ./tsconfig.json:/work/tsconfig.json
      - ./serve.json:/work/serve.json
      - ./public:/work/public/
      - ./scripts:/work/scripts/
      - ./src:/work/src/
      - ./vendor:/work/vendor/
    ports:
      # Serve the Frontend on the host
      - '${PORT}:${PORT}'
