version: '3.9'

services:
  cube-svc:
    container_name: cube-svc
    image: cube-svc:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      COCKROACH_DB_CONNECTION_STRING: ${COCKROACH_DB_CONNECTION_STRING}

      ENCRYPT_SECRET: ${ENCRYPT_SECRET}
      JWT_TOKEN_SECRET: ${JWT_TOKEN_SECRET}
      BREVO_API_KEY: ${BREVO_API_KEY}
      CONTACT_US_EMAIL: ${CONTACT_US_EMAIL}

      CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      CLOUDFLARE_STREAM_CUSTOMER_SUBDOMAIN: ${CLOUDFLARE_STREAM_CUSTOMER_SUBDOMAIN}
      CLOUDFLARE_R2_ACCESS_KEY_ID: ${CLOUDFLARE_R2_ACCESS_KEY_ID}
      CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${CLOUDFLARE_R2_SECRET_ACCESS_KEY}
      CLOUDFLARE_R2_BUCKET_NAME: ${CLOUDFLARE_R2_BUCKET_NAME}
      CLOUDFLARE_R2_PUBLIC_BUCKET_BASE_URL: ${CLOUDFLARE_R2_PUBLIC_BUCKET_BASE_URL}
