version: "3.9"

services:
  cube_frontend:
    container_name: ${PROJECT_NAME}_frontend
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      PROJECT_NAME: $PROJECT_NAME
    volumes:
      - ./.env:/work/.env
      - ./.env.example:/work/.env.example
      - ./.eslintignore:/work/.eslintignore
      - ./.eslintrc.json:/work/.eslintrc.json
      - ./.prettierignore:/work/.prettierignore
      - ./.prettierrc:/work/.prettierrc
      - ./Makefile.in-container.mk:/work/Makefile
      - ./package.json:/work/package.json
      - ./package-lock.json:/work/package-lock.json
      - ./tsconfig.json:/work/tsconfig.json
      - ./public:/work/public/
      - ./src:/work/src/
    ports:
      # Serve the Frontend on the host as available on port 14550
      - '3000:3000'
      # Serve the mocked API on the host as available on port 14550
      - '4550:4550'
