version: "3.9"

services:
  cube_frontend:
    container_name: ${PROJECT_NAME}_frontend
    build:
      context: .
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}_frontend
    environment:
      PROJECT_NAME: $PROJECT_NAME
    volumes:
      - ./.env:/work/.env
      - ./.env.example:/work/.env.example
      - ./.eslintignore:/work/.eslintignore
      - ./.eslintrc.json:/work/.eslintrc.json
      - ./.prettierignore:/work/.prettierignore
      - ./.prettierrc:/work/.prettierrc
      - ./Makefile.in-container.mk:/work/Makefile
      - ./package.json:/work/package.json
      - ./package-lock.json:/work/package-lock.json
      - ./tsconfig.json:/work/tsconfig.json
      - ./public:/work/public/
      - ./src:/work/src/
    ports:
      # Serve the Frontend on the host
      - '3000:3000'

  cube_interimapiserver:
    container_name: ${PROJECT_NAME}_interimapiserver
    build:
      context: ./interimapiserver/
      dockerfile: ./Dockerfile
    image: ${PROJECT_NAME}_interimapiserver
    environment:
      PROJECT_NAME: $PROJECT_NAME
    volumes:
      - ./interimapiserver/.env:/work/.env
      - ./interimapiserver/.env.example:/work/.env.example
      - ./interimapiserver/Makefile.in-container.mk:/work/Makefile
      - ./interimapiserver/package.json:/work/package.json
      - ./interimapiserver/package-lock.json:/work/package-lock.json
      - ./interimapiserver/tsconfig.json:/work/tsconfig.json
      - ./interimapiserver/src:/work/src/
    ports:
      # Serve the mocked API on the host
      - '4550:4550'
