version: '3.9'

services:
  cube_bff_microservice:
    container_name: ${PROJECT_NAME}_microservice
    build:
      context: .
      dockerfile: ${MICROSERVICE_DOCKERFILE}
    image: ${PROJECT_NAME}_microservice
    networks:
      - public_api
    environment:
      PROJECT_NAME: $PROJECT_NAME

      PORT: $PORT
      JWT_TOKEN_SECRET: $JWT_TOKEN_SECRET

    volumes:
      - ./.env.example:/work/.env.example
      - ./${ENV_FILE}:/work/.env
      - ./src:/work/src/
      - ./package-lock.json:/work/package-lock.json
      - ./package.json:/work/package.json
      - ./tsconfig.json:/work/tsconfig.json
    ports:
      # Serve the microservice on the host
      - '$PORT:$PORT'

  cube_bff_testrunner:
    profiles:
      - test
    container_name: ${PROJECT_NAME}_testrunner
    build:
      context: .
      dockerfile: test/Dockerfile
    image: ${PROJECT_NAME}_testrunner
    depends_on:
      - cube_bff_microservice
    networks:
      - public_api
    environment:
      PROJECT_NAME: $PROJECT_NAME

      # This must be the same as the service name here in the docker compose file.
      MICROSERVICE: cube_bff_microservice
      PORT: $PORT

      JWT_TOKEN_SECRET: $JWT_TOKEN_SECRET
    volumes:
      - ./.env.example:/work/.env.example
      - ./${ENV_FILE}:/work/.env
      - ./test/example-files:/work/example-files/
      - ./test/src:/work/src/
      - ./test/scripts:/work/scripts/
      - ./test/jest.config.js:/work/jest.config.js
      - ./test/package-lock.json:/work/package-lock.json
      - ./test/package.json:/work/package.json
      - ./test/tsconfig.json:/work/tsconfig.json

networks:
  public_api:
