version: '3.9'

services:
  cube_bff_x_identity_microservice:
    container_name: ${PROJECT_NAME}_microservice
    build:
      context: ../../identity
      dockerfile: ./${MICROSERVICE_DOCKERFILE}
    image: ${PROJECT_NAME}_microservice
    depends_on:
      - postgres
    networks:
      - internal_api
      - db
    environment:
      PROJECT_NAME: $PROJECT_NAME

      PORT: $PORT
      JWT_TOKEN_SECRET: $JWT_TOKEN_SECRET
      ENCRYPT_SECRET: $ENCRYPT_SECRET

      PROFILE_SERVICE_URL: http://cube_bff_x_identity_profile_mock_microservice:${PORT}

      PGHOST: postgres
      PGPORT: '5432'

      PGUSER: $POSTGRES_USER
      PGPASSWORD: $POSTGRES_PASSWORD
      PGDATABASE: $POSTGRES_DB
    volumes:
      - ../../identity/.env.example:/work/.env.example
      - ${ENV_FILE}:/work/.env
      - ../../identity/migrations:/work/migrations/
      - ../../identity/src:/work/src/
      - ../../identity/database.json:/work/database.json
      - ../../identity/package-lock.json:/work/package-lock.json
      - ../../identity/package.json:/work/package.json
      - ../../identity/tsconfig.json:/work/tsconfig.json

  cube_bff_x_identity_profile_mock_microservice:
    container_name: ${PROJECT_NAME}_profile_mock
    build:
      context: ../../profile/
      dockerfile: ./${MICROSERVICE_DOCKERFILE}
    image: ${PROJECT_NAME}_profile_mock
    depends_on:
      - postgres
    networks:
      - internal_api
      - db
    environment:
      PROJECT_NAME: $PROJECT_NAME

      PORT: $PORT
      JWT_TOKEN_SECRET: $JWT_TOKEN_SECRET

      PGHOST: postgres
      PGPORT: '5432'

      # For setting up multiple DBs in the same PostgreSQL Docker container, see
      # https://github.com/docker-library/docs/blob/master/postgres/README.md#initialization-scripts
      # TODO Keep those DBs separate?
      PGUSER: $POSTGRES_USER
      PGPASSWORD: $POSTGRES_PASSWORD
      PGDATABASE: $POSTGRES_DB
    volumes:
      - ../../profile/.env.example:/work/.env.example
      - ${PROFILE_MOCK_ENV_FILE}:/work/.env
      - ../../profile/migrations:/work/migrations/
      - ../../profile/src:/work/src/
      - ../../profile/database.json:/work/database.json
      - ../../profile/package-lock.json:/work/package-lock.json
      - ../../profile/package.json:/work/package.json
      - ../../profile/tsconfig.json:/work/tsconfig.json


  cube_bff_x_identity_gateway:
    container_name: ${PROJECT_NAME}_gateway
    build:
      context: ../
      dockerfile: ./${GATEWAY_DOCKERFILE}
    image: ${PROJECT_NAME}_gateway
    depends_on:
      - cube_bff_x_identity_microservice
    networks:
      - public_api
      - internal_api
    environment:
      PROJECT_NAME: $PROJECT_NAME

      PORT: $GATEWAY_PORT
      JWT_TOKEN_SECRET: $JWT_TOKEN_SECRET

      IDENTITY_SERVICE_URL: http://cube_bff_x_identity_microservice:${PORT}

      # These just get dummy values for this docker compose constellation.
      CLOUDFLARE_SERVICE_URL: http://cube_bff_x_identity_microservice:${PORT}
      CONTENT_SERVICE_URL: http://cube_bff_x_identity_microservice:${PORT}
      PROFILE_SERVICE_URL: http://cube_bff_x_identity_microservice:${PORT}

    volumes:
      - ../.env.example:/work/.env.example
      - ${GATEWAY_ENV_FILE}:/work/.env
      - ../src:/work/src/
      - ../package-lock.json:/work/package-lock.json
      - ../package.json:/work/package.json
      - ../tsconfig.json:/work/tsconfig.json

  postgres:
    container_name: ${PROJECT_NAME}_db
    image: postgres:15.1-alpine3.17
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: /var/lib/postgresql/data
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    networks:
      - db

  cube_bff_x_identity_testrunner:
    profiles:
      - test
    container_name: ${PROJECT_NAME}_testrunner
    build:
      context: ../../identity/
      dockerfile: ./test/Dockerfile
    image: ${PROJECT_NAME}_testrunner
    depends_on:
      - cube_bff_x_identity_gateway
    networks:
      - public_api

      # So that we can empty the DB before running the tests.
      - db
    environment:
      PROJECT_NAME: $PROJECT_NAME

      # This must be the same as the service name here in the docker compose file.
      MICROSERVICE: cube_bff_x_identity_gateway
      PORT: $GATEWAY_PORT

      PGHOST: postgres
      PGPORT: '5432'

      PGUSER: $POSTGRES_USER
      PGPASSWORD: $POSTGRES_PASSWORD
      PGDATABASE: $POSTGRES_DB

      JWT_TOKEN_SECRET: $JWT_TOKEN_SECRET
      ENCRYPT_SECRET: $ENCRYPT_SECRET
    volumes:
      - ../../identity/.env.example:/work/.env.example
      - ${ENV_FILE}:/work/.env
      - ../../identity/test/example-files:/work/example-files/
      - ../../identity/test/src:/work/src/
      - ../../identity/test/scripts:/work/scripts/
      - ../../identity/test/jest.config.js:/work/jest.config.js
      - ../../identity/test/package-lock.json:/work/package-lock.json
      - ../../identity/test/package.json:/work/package.json
      - ../../identity/test/tsconfig.json:/work/tsconfig.json

volumes:
  pgdata:

networks:
  public_api:
  internal_api:
  db:
