name: Publish VTT Prod

run-name: Publish VTT Prod @ ${{ github.sha }}

on:
  push:
    branches:
      - deploy-production
    paths:
      - "services/vtt/**"
      - ".github/workflows/publish-vtt-prod.yaml"
      - ".github/workflows/publish-vtt-reusable.yaml"

jobs:
  publish-service:
    uses: ./.github/workflows/publish-vtt-reusable.yaml
    with:
      ENV_NAME: prod
      GCP_WORKLOAD_IDENTITY_PROVIDER: projects/366271888053/locations/global/workloadIdentityPools/cube-prod/providers/github-actions
      GCP_SERVICE_ACCOUNT: service-deployer@cubecommons-prod.iam.gserviceaccount.com
      CLOUDFLARE_R2_BUCKET_NAME: cubecommons-prod
