name: Publish content microservice DEV

run-name: Publish content microservice DEV @ ${{ github.sha }}

on:
    push:
        branches:
            - deploy-dev
        paths:
            - "services/content/**"

            # This helps with debugging GHAs:
            - ".github/workflows/publish-content-microservice-dev.yaml"
            - ".github/workflows/publish-reusable.yaml"

jobs:
    publish-service:
        uses: ./.github/workflows/publish-reusable.yaml
        with:
            CODE_BASE_DIR: services/content
            GCP_PROJECT: cubecommons-dev
            GCP_REGION: northamerica-northeast2
            GCP_RUN_APPNAME: content
            GCP_WORKLOAD_IDENTITY_PROVIDER: projects/744911585239/locations/global/workloadIdentityPools/cube-dev/providers/github-actions
            GCP_SERVICE_ACCOUNT: docker-image-publisher@cubecommons-dev.iam.gserviceaccount.com

            GCP_RUN_OPTION_DB: --set-cloudsql-instances=cubecommons-dev:northamerica-northeast2:dev
            GCP_RUN_OPTION_ENV: --set-env-vars=PGPORT=5432,PGHOST=/cloudsql/cubecommons-dev:northamerica-northeast2:dev,PGDATABASE=cube_content,PGUSER=postgres
            GCP_RUN_OPTION_SECRETS: --set-secrets=JWT_TOKEN_SECRET=dev-jwt-token-secret:latest,PGPASSWORD=dev-db-password:latest,BREVO_API_KEY=dev-brevo-api-key:latest,REPORT_ABUSE_EMAIL=dev-report-abuse-email:latest
