name: Publish cloudflare microservice DEV

run-name: Publish cloudflare microservice DEV @ ${{ github.sha }}

on:
  push:
    branches:
      - main
    paths:
      - 'services/cloudflare/**'

      # This helps with debugging GHAs:
      - '.github/workflows/publish-cloudflare-microservice-dev.yaml'
      - '.github/workflows/publish-reusable.yaml'

jobs:
  publish-service:
    uses: ./.github/workflows/publish-reusable.yaml
    with:
      CODE_BASE_DIR: services/cloudflare
      GCP_PROJECT: cubecommons-dev
      GCP_REGION: northamerica-northeast2
      GCP_RUN_APPNAME: cloudflare
      GCP_WORKLOAD_IDENTITY_PROVIDER: projects/744911585239/locations/global/workloadIdentityPools/cube-dev/providers/github-actions
      GCP_SERVICE_ACCOUNT: docker-image-publisher@cubecommons-dev.iam.gserviceaccount.com
