name: Publish BFF gateway PROD

run-name: Publish BFF gateway PROD @ ${{ github.sha }}

on:
  push:
    branches:
      - main
    paths:
      - 'services/bff/**'

      # This helps with debugging GHAs:
      - '.github/workflows/publish-bff-gateway-prod.yaml'
      - '.github/workflows/publish-reusable.yaml'

jobs:
  publish-service:
    uses: ./.github/workflows/publish-reusable.yaml
    with:
      CODE_BASE_DIR: services/bff
      GCP_PROJECT: cubecommons-prod
      GCP_REGION: northamerica-northeast2
      GCP_RUN_APPNAME: bff
      GCP_WORKLOAD_IDENTITY_PROVIDER: projects/366271888053/locations/global/workloadIdentityPools/cube-prod/providers/github-actions
      GCP_SERVICE_ACCOUNT: service-deployer@cubecommons-prod.iam.gserviceaccount.com

      GCP_RUN_OPTION_MIN_INSTANCES: --min-instances=1
      GCP_RUN_OPTION_ENV: --set-env-vars=CLOUDFLARE_SERVICE_URL=https://cloudflare-ztbavieh4q-pd.a.run.app,CONTENT_SERVICE_URL=https://content-ztbavieh4q-pd.a.run.app,IDENTITY_SERVICE_URL=https://identity-ztbavieh4q-pd.a.run.app,PROFILE_SERVICE_URL=https://profile-ztbavieh4q-pd.a.run.app
      GCP_RUN_OPTION_SECRETS: --set-secrets=JWT_TOKEN_SECRET=prod-jwt-token-secret:latest
