name: Publish cloudflare microservice DEV

run-name: Publish cloudflare microservice DEV @ ${{ github.sha }}

on:
  push:
    branches:
      - deploy-dev
    paths:
      - 'services/cloudflare/**'

      # This helps with debugging GHAs:
      - '.github/workflows/publish-cloudflare-microservice-dev.yaml'
      - '.github/workflows/publish-reusable.yaml'

jobs:
  publish-service:
    uses: ./.github/workflows/publish-reusable.yaml
    with:
      CODE_BASE_DIR: services/cloudflare
      GCP_PROJECT: cubecommons-dev
      GCP_REGION: northamerica-northeast2
      GCP_RUN_APPNAME: cloudflare
      GCP_WORKLOAD_IDENTITY_PROVIDER: projects/744911585239/locations/global/workloadIdentityPools/cube-dev/providers/github-actions
      GCP_SERVICE_ACCOUNT: docker-image-publisher@cubecommons-dev.iam.gserviceaccount.com

      GCP_RUN_OPTION_DB: --set-cloudsql-instances=cubecommons-dev:northamerica-northeast2:dev
      GCP_RUN_OPTION_ENV: --set-env-vars=PGPORT=5432,PGHOST=/cloudsql/cubecommons-dev:northamerica-northeast2:dev,PGDATABASE=cube_cloudflare,PGUSER=postgres,CLOUDFLARE_ACCOUNT_ID=812b8374abe5aa28e1ff4b96f82e1340,CLOUDFLARE_STREAM_CUSTOMER_SUBDOMAIN=customer-ayah89x7bps0l5b8.cloudflarestream.com,CLOUDFLARE_R2_BUCKET_NAME=cubecommons-dev,CLOUDFLARE_R2_PUBLIC_BUCKET_BASE_URL=https://files-dev.cubecommons.ca
      GCP_RUN_OPTION_SECRETS: --set-secrets=JWT_TOKEN_SECRET=dev-jwt-token-secret:latest,CLOUDFLARE_R2_ACCESS_KEY_ID=dev-cloudflare-r2-access-key-id:latest,CLOUDFLARE_API_TOKEN=dev-cloudflare-api-token:latest,CLOUDFLARE_R2_SECRET_ACCESS_KEY=dev-cloudflare-r2-secret-access-key:latest,PGPASSWORD=dev-db-password:latest
