name: Publish BFF gateway DEV

run-name: Publish BFF gateway DEV @ ${{ github.sha }}

on:
  push:
    branches:
      - deploy-dev
    paths:
      - 'services/bff/**'

      # This helps with debugging GHAs:
      - '.github/workflows/publish-bff-gateway-dev.yaml'
      - '.github/workflows/publish-reusable.yaml'

jobs:
  publish-service:
    uses: ./.github/workflows/publish-reusable.yaml
    with:
      CODE_BASE_DIR: services/bff
      GCP_PROJECT: cubecommons-dev
      GCP_REGION: northamerica-northeast2
      GCP_RUN_APPNAME: bff
      GCP_WORKLOAD_IDENTITY_PROVIDER: projects/744911585239/locations/global/workloadIdentityPools/cube-dev/providers/github-actions
      GCP_SERVICE_ACCOUNT: docker-image-publisher@cubecommons-dev.iam.gserviceaccount.com

      GCP_RUN_OPTION_MIN_INSTANCES: --min-instances=1
      GCP_RUN_OPTION_ENV: --set-env-vars=CLOUDFLARE_SERVICE_URL=https://cloudflare-tjjg4pjowa-pd.a.run.app,CONTENT_SERVICE_URL=https://content-tjjg4pjowa-pd.a.run.app,IDENTITY_SERVICE_URL=https://identity-tjjg4pjowa-pd.a.run.app,PROFILE_SERVICE_URL=https://profile-tjjg4pjowa-pd.a.run.app
      GCP_RUN_OPTION_SECRETS: --set-secrets=JWT_TOKEN_SECRET=dev-jwt-token-secret:latest
